#%%
print("Arithmetic Exercise Generator")
print("Random arithemtic questions will be generated.")
print("Enter 'e' at any time to exit the propgram.")

import random

while True:
    op1 = random.randint(1, 20)
    op2 = random.randint(1, 20)
    op = random.randint(1, 3)
    if op == 1:  # Addition
        ans = op1 + op2
        qn = str(op1) + " + " + str(op2)
    elif op == 2:  # Subtraction
        ans = op1 - op2
        qn = str(op1) + " - " + str(op2)
    elif op == 3:  # Multiplication
        ans = op1 * op2
        qn = str(op1) + " * " + str(op2)

    response = input("What is " + qn + "? ")
    # Check for exit first
    if response == "e": break

    # If not exit, then convert and check answer
    response = int(response)
    if response == ans:
        print("Correct!", end=" ")
        continue

    # Handle when incorrect
    while True:
        response = input("Wrong. Try again! What is " + qn + "? ")

        # Reduplicate logic above
        if response == "e": break  # will break out of this inner while loop
        response = int(response)
        if response == ans:
            print("Correct!", end=" ")
            break

    # End program if 'e' entered during 'wrong' loop.
    if response == "e": break

#%% Generated by an LLM
import random

print("Arithmetic Exercise Generator")
print("Random arithmetic questions will be generated.")
print("Enter 'e' at any time to exit the program.")

while True:
    op = random.choice(['+', '-', '*', '/'])
    if op == '+':
        a = random.randint(1, 10)
        b = random.randint(1, 10)
        answer = a + b
    elif op == '-':
        a = random.randint(1, 20)
        b = random.randint(1, a)
        answer = a - b
    elif op == '*':
        a = random.randint(1, 10)
        b = random.randint(1, 10)
        answer = a * b
    else:  # Division
        b = random.randint(1, 10)
        c = random.randint(1, 10)
        a = b * c
        answer = c

    for attempt in range(2):
        user_input = input(f"What is {a} {op} {b}? ").strip()
        if user_input == 'e':
            break

        try:
            user_answer = int(user_input)
        except ValueError:
            user_answer = None

        if user_answer is not None and user_answer == answer:
            print("Correct! ", end='')
            break
        else:
            if attempt == 0:
                print("Wrong. Try again! ", end='')
            else:
                print(f"Wrong. The correct answer is {answer}.")

    if user_input == 'e':
        print("exiting...")
        break
